import Zcash.Security.KeyBinding.Instance
import Zcash.Security.KeyBinding.Probability
import Zcash.Security.Common.Birthday
import Zcash.Security.BindingSignature.Orchard
import Zcash.Security.BindingSignature.Sapling
import Zcash.Meta.AxiomCheck
import Zcash.Snark.Soundness.CommitFold
import Zcash.Snark.Soundness.Vesta
import Zcash.Snark.Soundness.Deployed.ConcreteBounds
import Zcash.Snark.Soundness.AGM.BindingSignature
import Zcash.Snark.Soundness.AGM.Capstone
import Zcash.Snark.Soundness.AGM.ProbabilityVesta
import Zcash.Snark.Soundness.Forking.Adversary
import Zcash.Snark.Soundness.Composition.Bridge
import Zcash.Snark.Soundness.Multiopen.BudgetedExtraction
import Zcash.Snark.Soundness.VestaBudget
import Zcash.Snark.Soundness.FoldSplit
import Zcash.Snark.Soundness.ConstraintSatisfaction
import Zcash.Snark.Soundness.LookupRows
import Zcash.Snark.Soundness.LookupInstantiation
import Zcash.Snark.Soundness.Multiopen.ConstraintResolver
import Zcash.Snark.Soundness.GrandProductBridge
import Zcash.Snark.Soundness.LookupAssembly
import Zcash.Snark.Soundness.PermutationRows
import Zcash.Snark.Soundness.PermutationInstantiation
import Zcash.Snark.Soundness.PermutationSemantics
import Zcash.Snark.Soundness.CircuitSatisfaction
import Zcash.Snark.Soundness.OperationCopies
import Zcash.Snark.Soundness.OperationLookups
import Zcash.Snark.Soundness.OperationGates
import Zcash.Snark.Soundness.OperationFixed
import Zcash.Snark.Soundness.LookupSemantics
import Zcash.Snark.Soundness.CircuitIntegration
import Zcash.Snark.Soundness.TopLevelCircuit
import Zcash.Snark.Soundness.TopLevelAssignment
import Zcash.Snark.Soundness.PolynomialEnvironment
import Zcash.Snark.Soundness.DomainSelectors
import Zcash.Snark.Soundness.InstanceCommitment
import Zcash.Snark.Soundness.ActionAssignment
import Zcash.Snark.Soundness.ActionStatement
import Zcash.Snark.Soundness.Composition.Decomposition
import Zcash.Snark.Soundness.Composition.Residual
import Zcash.Snark.Soundness.Composition.Prefixes
import Zcash.Snark.Soundness.Composition.Completeness

/-!
# Trust boundary, build-checked

The library-wide census that makes the trust claims build-time checks rather than prose: a change
that widens a declaration's trusted base — a `sorry` reached through some dependency, an unexpected
axiom, or `native_decide` where none was permitted — fails this file rather than passing silently.

Two commands from `Zcash.Meta.AxiomCheck`, per the breaks-as-computed-data discipline (see
`Zcash.Security.RandomOracle`):

* **Computed break reductions** get `assert_computable`: the declaration is a plain `def` — not a
  theorem, not marked `noncomputable` — with axioms bounded by `propext` / `Quot.sound`.
  `+choice` additionally permits `Classical.choice`; with the plain-`def` check this asserts
  choice enters only through erased `Prop` certificate fields, so the break data cannot have been
  conjured from mere propositional existence.
* **Theorems** get `assert_axioms`, an upper bound at the standard tier
  (`propext` / `Classical.choice` / `Quot.sound`). Both commands reject `sorryAx`.
-/

open Zcash.Security.KeyBinding Zcash.Security.RandomOracle Zcash.Security.Birthday
open Zcash.Security.Ledger Zcash.Security.BindingSignature
open Zcash.Meta

/-! ## Key binding — computed break reductions -/

assert_computable Zcash.Security.RandomOracle.CollisionUpToSign.ofOpeningBreak +choice
assert_computable Zcash.Security.RandomOracle.CollisionUpToSign.ofBreak +choice

/-! ## Key binding — theorems -/

assert_axioms Zcash.Security.KeyBinding.Extractor.card_ivk_ge
assert_axioms Zcash.Security.KeyBinding.commit_scalar_pm
assert_axioms Zcash.Security.KeyBinding.rivk_eq_finalOracle
assert_axioms Zcash.Security.KeyBinding.sameIvk_finalOracle_pm
assert_axioms Zcash.Security.KeyBinding.openingBreak_finalOracle_pm
assert_axioms Zcash.Security.KeyBinding.break_finalOracle_pm
assert_axioms Zcash.Security.KeyBinding.residual_of_finalQuery_eq
assert_axioms Zcash.Security.KeyBinding.nk_pinned
assert_axioms Zcash.Security.KeyBinding.ak_pinned
assert_axioms Zcash.Security.KeyBinding.qk_or_sk_pinned
assert_axioms Zcash.Security.KeyBinding.collision_mem_shifted_pm
assert_axioms Zcash.Security.KeyBinding.toInterface

/-! ## Birthday bound -/

assert_axioms Zcash.Security.Birthday.card_shifted_pm_collision_le
assert_axioms Zcash.Security.Birthday.shifted_pm_collision_fraction_le
assert_axioms Zcash.Security.Birthday.birthday_closed_form

/-! ## Key binding — whole-table random-oracle model -/

assert_computable Zcash.Security.KeyBinding.finalQueryEquiv
assert_axioms Zcash.Security.KeyBinding.eval_restrict
assert_axioms Zcash.Security.KeyBinding.pair_shifted_collision_measure_le
assert_axioms Zcash.Security.KeyBinding.finset_shifted_collision_measure_le
assert_axioms Zcash.Security.KeyBinding.ofBreak_queries
assert_axioms Zcash.Security.KeyBinding.break_measure_le
assert_computable Zcash.Security.KeyBinding.badList
assert_axioms Zcash.Security.KeyBinding.mem_badList
assert_axioms Zcash.Security.KeyBinding.badList_measure_le
assert_axioms Zcash.Security.KeyBinding.escapesWithHistory
assert_axioms Zcash.Security.KeyBinding.escapesWithHistory_measure_le
assert_axioms Zcash.Security.KeyBinding.CollidesDuring
assert_axioms Zcash.Security.KeyBinding.CollidesDuring.of_pair
assert_axioms Zcash.Security.KeyBinding.sum_two_mul_add
assert_axioms Zcash.Security.KeyBinding.collidesDuring_measure_le
assert_axioms Zcash.Security.KeyBinding.queries_pair_collision_measure_le
assert_computable Zcash.Security.KeyBinding.derivQueries
assert_axioms Zcash.Security.KeyBinding.break_measure_le_adaptive
assert_axioms Zcash.Security.KeyBinding.break_measure_le_of_queryBound
assert_axioms Zcash.Security.KeyBinding.toOuterMeasure_bind_le
assert_axioms Zcash.Security.KeyBinding.break_measure_le_mixture
assert_axioms Zcash.Security.KeyBinding.uniformOfFintype_prod
assert_computable Zcash.Security.KeyBinding.evalEquiv
assert_axioms Zcash.Security.KeyBinding.uniform_triple_eval
assert_axioms Zcash.Security.KeyBinding.break_measure_le_product
assert_axioms Zcash.Security.toInterface_break_measure_le

/-! ## Ledger-layer break reductions

These data-producing reductions rest on `propext` and `Quot.sound` only — no `Classical.choice`
even in erased positions, which is the strict (flagless) `assert_computable` tier. -/

assert_computable Collision.upToSign
assert_computable Merkle.collisionOfWrongLeaf
assert_computable noteCommitBreakOfNe
assert_computable Zcash.Security.Ledger.nfOldEqOrBreak +choice

/-! ## Binding-signature relation reductions

Unlike the ledger break reductions, these depend on `Classical.choice` (`+choice`). It enters
only through erased `Prop` certificate fields (the arithmetic side proofs); the relation
coefficients themselves are direct terms of the inputs, and the plain-`def` check means the data
cannot have been conjured from mere propositional existence. -/

assert_computable NontrivialRelation.ofImbalance +choice
assert_computable NontrivialRelation.ofBundleModImbalance +choice
assert_computable NontrivialRelation.ofBundleIntImbalance +choice
assert_computable NontrivialRelation.ofOrchardImbalance +choice
assert_computable NontrivialRelation.ofSaplingImbalance +choice

/-!
## SNARK soundness stack

The census also carries the SNARK binding and knowledge-soundness reductions, consolidated here
from the former per-directory files and, like the key-binding and ledger sections above, expressed
through the `Zcash.Meta.AxiomCheck` macros rather than the older `assert_no_sorry` +
`#guard_msgs`-pinned `#print axioms` idiom:

* **Computed break reductions** — the data-producing `def`s that extract a discrete-log relation
  from a collision, fold, peel, or fork — get `assert_computable`: a plain `def`, not marked
  `noncomputable`. `Classical.choice` enters only through erased `Prop` certificate fields
  (`+choice`); the relation coefficients are direct terms of the inputs, so the break data cannot
  have been conjured from mere propositional existence. Vesta-instantiated producers additionally
  inherit CompElliptic's `native_decide` curve point-count axiom (`+native`).
* **Theorems** — the probability-layer bounds, the knowledge-soundness and binding endpoints across
  all adversary models, the DL capstones, and the run-time/query-charge lemmas — get
  `assert_axioms`, bounding the trusted base at the standard tier (`propext` / `Classical.choice` /
  `Quot.sound`), with `+native` on the Vesta-instantiated endpoints.
-/

open Zcash.Snark

/-! ### Binding reductions from IPA/CommitFold collisions -/

assert_computable NontrivialDLRelation.ofCollision +choice
assert_computable NontrivialDLRelation.ofIpaOpenings +choice

/-! ### Verifier-soundness capstones -/

assert_axioms deployedAccepts_verifierEq
assert_axioms orchard_verifier_sound_conditional
assert_axioms orchard_verifier_deployed_opening_of_forked
assert_axioms orchard_verifier_deployed_constraint_of_forked
assert_axioms orchard_verifier_sound_vesta_conditional +native
assert_axioms orchard_verifier_vesta_opening_of_forked +native
assert_axioms orchard_verifier_vesta_constraint_of_forked +native

/-! ### Deployed binding-reduction breaks

The binding reductions return computed data (plain `def`s); the same treatment covers the forking
reductions `ipa_extractV`, `ipaRelation_extract`, `produceDeployed`, `deployed_forking_tree`, and
`deployed_forking_relation`, each computing its witness from an explicit certificate. -/

assert_computable NontrivialRelation.ofCombinationCollision +choice
assert_computable NontrivialRelation.ofFoldedGens +choice
assert_computable NontrivialRelation.ofLeafPeel +choice
assert_computable NontrivialRelation.ofDeployedTree +choice
assert_computable NontrivialRelation.ofUnopenedFork +choice
assert_computable NontrivialRelation.ofUnopenedForkVesta +choice +native
assert_computable ipa_extractV +choice
assert_computable ipaRelation_extract +choice
assert_computable produceDeployed +choice
assert_computable deployed_forking_tree +choice
assert_computable deployed_forking_relation +choice

/-! ### AGM / Fiat–Shamir soundness

The AGM kernels compute representations, openings, relations, certificates, and deployed instances
as data (`assert_computable`); the probability layer, the knowledge-soundness and binding endpoints,
and the run-time bounds are theorems (`assert_axioms`). -/

assert_computable discreteLogOfBasis_of_relation +choice
assert_computable DLChallengeGame.solveFromRelation +choice
assert_computable fixedSlotExtractOrMiss +choice
assert_computable AugmentedRelationWitness.toAlgebraicRelationWitness +choice
assert_computable relationWitnessOfCollision +choice
assert_computable discreteLogOfAugmentedRelationAtChallenge +choice
assert_computable separateOrRelationWitness +choice
assert_computable relationOfFoldGensWitness +choice
assert_computable deployedLeafPeelWitness +choice
assert_computable deployedToAcceptVWitness +choice
assert_computable algebraicRelationOfDeployedAccept +choice
assert_axioms AlgebraicProver.toProver
assert_axioms AlgebraicDForkCert.toDForkCert
assert_axioms algebraicProverAccept_forkValid
assert_computable deployedAlgebraicForkingRelation +choice
assert_axioms deployed_forking_relation_shifted
assert_axioms deployedAlgebraicForkingRelation_shifted
assert_computable deployedAlgebraicForkingFixedSlot +choice
assert_axioms DeployedAlgebraicForkingInstance.run
assert_axioms DeployedAlgebraicForkingInstance.ProducesRelation
assert_axioms deployedAlgebraicRelationProduced
assert_axioms deployedAlgebraicRelationEvent
assert_computable deployedAlgebraicRelationFinder +choice
assert_axioms deployedAlgebraicRelationFinder_isSome_iff
assert_computable deployedAlgebraicRelation +choice
assert_computable deployedAlgebraicRelationWitness +choice
assert_axioms orchardDeployedAlgebraicForkingFixedSlot +native
assert_axioms orchardDeployedRelationSet +native
assert_axioms OrchardUniformURSIdentification +native
assert_axioms orchardGeneratorROSetup
assert_axioms orchardGeneratorROBasis
assert_axioms orchard_uniformURSIdentification_of_generatorRO +native
assert_axioms recursiveAlgebraicForkFrom
assert_axioms recursiveAlgebraicForkFrom_realizes
assert_axioms algebraicForkCertAttempt +native
assert_axioms algebraicForkCertAttempt_valid +native
assert_axioms computedDeployedAlgebraicInstance +native
assert_axioms computedAlgebraicInstanceFailure_measure_le +native
assert_axioms AlgebraicRelationWitness.augment
assert_axioms DeployedAlgebraicForkingInstance.runRelation
assert_axioms DeployedAlgebraicForkingInstance.runRelation_isSome_of_mismatch
assert_computable DeployedAlgebraicForkingInstance.runToSnark +choice +native
assert_axioms ComputedAlgebraicFSFamily.relationFinder +native
assert_axioms ComputedAlgebraicFSFamily.relationFinder_isSome_of_bindingWin +native
assert_axioms ComputedAlgebraicFSFamily.snarkRelationFinder +native
assert_axioms ComputedAlgebraicFSFamily.snarkRelation_prob_le_of_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.acceptExtractionFailure_measure_le +native
assert_axioms ComputedAlgebraicFSFamily.snarkNonRelationFailure +native
assert_axioms ComputedAlgebraicFSFamily.snarkNonRelationFailure_measure_le +native
assert_axioms ComputedAlgebraicFSFamily.snarkFailure_prob_le_of_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.snarkFailure_prob_le_of_textbookDL_full +native
assert_axioms ComputedAlgebraicFSFamily.snarkFailure_prob_le_of_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.snarkFailure_prob_le_of_generatorRO_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.binding_prob_le_of_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.binding_prob_le_of_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.binding_prob_le_of_generatorRO_textbookDL +native
assert_axioms ComputedAlgebraicFSFamily.ReductionEfficient +native
assert_axioms ComputedAlgebraicFSFamily.reductionEfficient_exists +native
assert_axioms ComputedAlgebraicFSFamily.instanceAttempt_runs_eq +native
assert_axioms ComputedAlgebraicFSFamily.reductionEfficient_exponential +native
assert_axioms ComputedAlgebraicFSFamily.DiscreteLogRelationHardFor +native
assert_axioms ComputedAlgebraicFSFamily.knowledgeSoundness_under_DL +native
assert_axioms ComputedAlgebraicFSFamily.binding_under_DL +native
assert_axioms bindingWin_unbounded_measure_le +native
assert_axioms queryCharge
assert_axioms queryCharge_sum_mul_le
assert_axioms le_queryCharge_of_mem_queries
assert_axioms mem_queries_dedup
assert_axioms applyUpdates_apply_mem_nodup
assert_axioms queryCharge_sum_mul_le_table_budget
assert_axioms steeredCharge_context_sum_mul_le
assert_axioms steeredCharge_context_sum_mul_le_table_budget
assert_axioms steeredCharge_sum_mul_le
assert_axioms scanCandidate_self
assert_axioms self_mem_goodChallenges_iff
assert_axioms scanRank_insert_erase
assert_axioms scanRank_insert_eq_filter
assert_axioms goodChallengesAt
assert_axioms OracleComp.queries_queryList
assert_axioms recursiveAlgebraicForkFrom_node_runs_le_gated
assert_axioms OracleComp.queries_bind
assert_axioms OracleComp.mem_queries_completing
assert_axioms scanCandidateAt
assert_axioms scanCandidateAt_fork
assert_axioms scanCandidateAt_update
assert_axioms goodChallengesAt_fork
assert_axioms goodChallengesAt_update
assert_axioms sum_card_scanRank_erase_lt_le
assert_axioms OracleComp.restrictSum
assert_axioms fsWinsFull_restrictSum_le
assert_axioms ComputedAlgebraicFSFamilyRand.determinize
assert_axioms ComputedAlgebraicFSFamilyRand.binding_prob_le_of_textbookDL_rand +native
assert_axioms ComputedAlgebraicFSFamilyRand.snarkFailure_prob_le_of_textbookDL_rand +native
assert_axioms ComputedAlgebraicFSFamily.snarkFailureEvent +native
assert_axioms ComputedAlgebraicFSFamilyRand.foldedRelationFinder +native
assert_axioms ComputedAlgebraicFSFamilyRand.binding_prob_le_of_foldedTextbookDL_rand +native
assert_axioms ComputedAlgebraicFSFamilyRand.foldedSnarkRelationFinder +native
assert_axioms ComputedAlgebraicFSFamilyRand.snarkFailure_prob_le_of_foldedTextbookDL_rand +native
assert_computable ComputedAlgebraicFSFamilyUnbounded.globalReachSet +choice
assert_axioms ComputedAlgebraicFSFamilyUnbounded.reachSet_subset_globalReachSet
assert_computable ComputedAlgebraicFSFamilyUnbounded.splitFamilyRand +choice
assert_axioms ComputedAlgebraicFSFamilyUnbounded.run_splitFamilyRand_adversary
assert_axioms ComputedAlgebraicFSFamilyUnbounded.binding_prob_le_of_unbounded_foldedTextbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.snarkFailure_prob_le_of_unbounded_foldedTextbookDL +native
assert_axioms uniformURS_basis_transfer +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.snarkFailureEventUnbounded +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.snarkFailure_prob_le_of_unbounded_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.snarkFailure_prob_le_of_unbounded_generatorRO_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.bindingEventUnbounded +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.binding_prob_le_of_unbounded_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnbounded.binding_prob_le_of_unbounded_generatorRO_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.determinize
assert_computable ComputedAlgebraicFSFamilyUnboundedRand.globalReachSet +choice
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.reachSet_subset_globalReachSet
assert_computable ComputedAlgebraicFSFamilyUnboundedRand.splitFamilyRand +choice
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.run_splitFamilyRand_adversary
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.binding_prob_le_of_unboundedRand_foldedTextbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.snarkFailure_prob_le_of_unboundedRand_foldedTextbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.snarkFailureEventUnboundedRand +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.snarkFailure_prob_le_of_unboundedRand_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.snarkFailure_prob_le_of_unboundedRand_generatorRO_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.bindingEventUnboundedRand +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.binding_prob_le_of_unboundedRand_uniformURS_textbookDL +native
assert_axioms ComputedAlgebraicFSFamilyUnboundedRand.binding_prob_le_of_unboundedRand_generatorRO_textbookDL +native
assert_axioms recursiveAlgebraicForkFrom_node_runs_le
assert_axioms recursiveAlgebraicFork_sum_runs_le_unconditional
assert_axioms recursiveAlgebraicFork_oracle_tape_sum_runs_le_unconditional
assert_axioms recursiveAlgebraicForkFrom_sum_runs_le_of_forkSpread
assert_axioms recursiveAlgebraicFork_sum_runs_le_of_forkSpread
assert_axioms AlgebraicPoint.point_eq_components +native
assert_axioms Msm.eval_repr +native
assert_axioms RepresentedMultiopen.ofCoveredList +native
assert_axioms AlgebraicWfProof.ofRepresented +native
assert_axioms assembleQueries_points_mem
assert_axioms constructIntermediateSets_ref_mem
assert_axioms multiopenMsm_points_mem
assert_axioms AlgebraicWfProof.ofStandard +native
assert_axioms OracleComp.reachSet
assert_axioms OracleComp.run_congr_reachSet
assert_axioms OracleComp.restrictTo
assert_axioms OracleComp.splitDomain
assert_axioms finite_domain_restriction
assert_axioms fsWinsFull_mapDomain_measure_eq
assert_axioms fsWinsFull_splitDomain
assert_axioms fsWinsFull_unbounded_measure_le
assert_axioms truncateTranscript
assert_computable Zcash.Security.BindingSignature.NontrivialRelation.toAlgebraicRelationWitness +choice
assert_computable Zcash.Security.BindingSignature.NontrivialRelation.toDiscreteLog +choice
assert_axioms Zcash.Security.BindingSignature.orchardImbalanceToDiscreteLog
assert_axioms Zcash.Security.BindingSignature.saplingImbalanceToDiscreteLog
assert_axioms hitProb_ge_inv_card
assert_axioms relSet_card_le_succSet_card
assert_axioms reduction_advantage_ge
assert_axioms relation_prob_le_of_DL
assert_axioms winSet_card
assert_axioms textbook_winProb_eq_succProb
assert_axioms relation_prob_le_of_textbookDL
assert_axioms orchard_relation_prob_le_of_DL +native
assert_axioms orchard_reduction_advantage_ge +native
assert_axioms orchard_relation_prob_le_of_textbookDL +native
assert_axioms commitment_binding_prob_le_of_textbookDL +native
assert_axioms orchard_deployed_reduction_advantage_ge +native
assert_axioms orchard_deployed_relation_prob_le_of_textbookDL +native
assert_axioms orchard_deployed_relation_set_eq_relSet +native
assert_axioms orchard_deployed_relation_event_prob_le_of_textbookDL +native
assert_axioms orchard_deployed_relation_prob_eq_of_uniformURS +native
assert_axioms orchard_deployed_relation_prob_le_of_uniformURS_textbookDL +native
assert_axioms orchard_deployed_relation_prob_le_of_generatorRO_textbookDL +native

/-! ### Fork-tree knowledge error

The closed form of the fork-tree knowledge error and its evaluation over the deployed Orchard
parameters. All theorems, so `assert_axioms`: the arithmetic runs on `Nat`/`ℝ≥0∞` and the deployed
field cardinality comes from `ZMod.card`, so no compiler trust enters here. -/

assert_axioms kerr_mul_card
assert_axioms kerr_eq
assert_axioms kerr_div_card
assert_axioms deployed_forking_knowledge_error
assert_axioms deployed_forking_knowledge_error_captured

/-! ### Circuit integration

The generic constraint decomposition, decoded-column bridge, top-level Clean semantics, and
Action statement adapter carried by the circuit-soundness integration. -/

assert_axioms deployed_value_check_node_binding
assert_axioms deployed_member_node_binding
assert_axioms orchard_verifier_vesta_member_constraint_derived +native
assert_axioms ipaRelation_deployed_of_instance +native
assert_axioms member_snark_of_instance +native
assert_axioms snarkRelation_of_memberColumns
assert_axioms SnarkRelation.and_satisfies
assert_axioms orchard_verifier_sound_vesta_computed +native
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL +native
assert_axioms instanceAttempt_provenance +native
assert_axioms ipaRelation_deployed_of_openings_agree +native
assert_axioms shift_eq_zero_of_openings_agree +native
assert_axioms uniformOfFintype_heavy_fiber_lt
assert_axioms deployed_value_check_node_binding_budgeted
assert_axioms deployed_member_node_binding_budgeted
assert_axioms deployed_member_budget
assert_axioms decodedColumnFamily_of_batch_openings
assert_axioms deployedCommitment_x4_batch
assert_axioms multiopenValue_x4_batch
assert_axioms x1_batch_open_soundV
assert_axioms member_binding_of_x1_samples
assert_axioms deployed_witness_member_binding
assert_axioms deployed_witness_two_level
assert_axioms node_binding_of_samples
assert_axioms uniformChallenge_szBadSet
assert_axioms uniformChallenge_szGoodSet
assert_axioms uniformChallenge_quotient_szBadSet
assert_axioms uniformChallenge_szBadSet_union
assert_axioms exists_accepting_good_challenge
assert_axioms exists_accepting_good_challenge_quotient
assert_axioms orchard_verifier_vesta_decoded_constraint_of_forked_x4 +native
assert_axioms orchard_verifier_vesta_forking_constraint_deployed_x4 +native
assert_axioms orchard_verifier_vesta_member_constraint_deployed_x4 +native
assert_axioms orchard_verifier_vesta_member_constraint_deployed_terminal +native
assert_axioms deployed_member_node_binding_at_point_budgeted
assert_axioms orchard_verifier_vesta_member_constraint_budgeted +native
assert_axioms member_relation_or_dlr_of_instance_budgeted +native
assert_axioms member_snark_of_instance_budgeted +native
assert_axioms orchard_verifier_sound_vesta_budgeted +native
assert_axioms cleanOpening_provenance +native
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL_budgeted +native
assert_axioms vanishing_query_mem_assembleQueries
assert_axioms assembleQueries_vanishingH_unique
assert_axioms constructIntermediateSets_unique_comm_routed
assert_axioms vanishing_slot_routed
assert_axioms hfold_of_expectedHEval_binding
assert_axioms hfold_of_vanishing_slot_binding
assert_axioms deployedAccepts_xn_ne_one
assert_axioms hfold_of_member_budget
assert_axioms permutationExpressions_map
assert_axioms lookupExpressions_map
assert_axioms subProofConstraints_map
assert_axioms allConstraints_map
assert_axioms subProofExpressions_eq
assert_axioms allExpressions_eq
assert_axioms eval_constraintPolys
assert_axioms eval_combineConstraints
assert_axioms eval_combineConstraints_deployed
assert_axioms hfold_of_constraint_polys
assert_axioms ConstraintPolyModel.constraints_eq_constraintPolys
assert_axioms ConstraintPolyModel.gate_mem_constraints
assert_axioms ConstraintPolyModel.permutation_mem_constraints
assert_axioms ConstraintPolyModel.lookup_mem_constraints
assert_axioms ConstraintPolyModel.lookupExpression_mem_lookupConstraints
assert_axioms ConstraintSatisfaction.of_all
assert_axioms ConstraintSatisfaction.lookupExpression
assert_axioms permutation_start_mem
assert_axioms permutation_end_mem
assert_axioms permutation_chain_mem
assert_axioms permutation_step_mem
assert_axioms lookup_start_mem
assert_axioms lookup_end_mem
assert_axioms lookup_product_step_mem
assert_axioms lookup_run_start_mem
assert_axioms lookup_run_step_mem
assert_axioms ConstraintSatisfaction.lookupStart
assert_axioms ConstraintSatisfaction.lookupEnd
assert_axioms ConstraintSatisfaction.lookupProductStep
assert_axioms ConstraintSatisfaction.lookupRunStart
assert_axioms ConstraintSatisfaction.lookupRunStep
assert_axioms constraints_dvd_of_good_y
assert_axioms telescope_running_product
assert_axioms grandProduct_eq_or_cell_eq_zero
assert_axioms multiset_pair_eq_of_prod_eval_eq
assert_axioms cellPairs_eq_of_running_product
assert_axioms perm_copy_constraints_of_running_product
assert_axioms prod_map_chunkedCellPairs
assert_axioms chunkedCellPairs_eq_of_running_product
assert_axioms perm_copy_constraints_of_chunked_running_product
assert_axioms telescope_chunks
assert_axioms telescope_chunks_variable_width
assert_axioms chunkedGrandProduct_eq_or_cell_eq_zero
assert_axioms lookup_multisets_of_prod_eval_eq
assert_axioms lookup_multisets_of_diff_eq_zero
assert_axioms lookup_subset_of_components
assert_axioms lookup_subset_of_prod_eval_eq
assert_axioms eval_lookupEvalPolys_productNextEval
assert_axioms eval_lookupEvalPolys_permutedInputInvEval_succ
assert_axioms lookup_product_row_recurrence
assert_axioms lookup_run_start_of_dvd
assert_axioms lookup_run_step_of_dvd
assert_axioms lookup_run_structure_of_dvd
assert_axioms lookup_product_eq_or_factor_eq_zero
assert_axioms deployed_lookup_subset
assert_axioms mem_assembleQueries_of_mem_subProofLookupQueries
assert_axioms constraintModelOfResolver_lookups
assert_axioms lookupEntry_mem_lookupEntriesOfResolver
assert_axioms lookupEntry_mem_constraintModelOfResolver
assert_axioms eval_lookupEntriesOfResolver
assert_axioms eval_lookupEntriesOfResolver_of_assembleQueries
assert_axioms eval_constraintModelOfResolver_lookups
assert_axioms eval_constraintModelOfResolver_lookups_of_assembleQueries
assert_axioms ConstraintSatisfaction.lookupConstraintsDvdOfResolver
assert_axioms query_eq_of_noDuplicateCommitmentPoint
assert_axioms constructIntermediateSets_query_routed
assert_axioms constructIntermediateSets_query_eval
assert_axioms assembleQueries_instance_commitment
assert_axioms constructIntermediateSets_member_provenance
assert_axioms assembledQueryMemberRoute
assert_axioms assembledQueryMemberRoute_faithful
assert_axioms deployedMemberRef_eq_instanceCommitment
assert_axioms assembledQueryRoutingConditions_of_assemble?_eq_some
assert_axioms decodedPolynomialResolver_opens_or_relation
assert_axioms eval_lookupEntriesOfDecodedResolver_or_relation
assert_axioms permChunk_left_eq_prod
assert_axioms permChunk_right_eq_prod
assert_axioms permChunkExpression_eq
assert_axioms eval_eq_zero_of_dvd_vanishing
assert_axioms perm_row_recurrence
assert_axioms running_product_start
assert_axioms running_product_end
assert_axioms running_product_chain
assert_axioms name_injective_of_coset
assert_axioms deployed_perm_copy_constraints
assert_axioms deployed_perm_copy_constraints_all_chunks
assert_axioms permutationLastEval_isSome
assert_axioms eval_permutationSetsOfResolver
assert_axioms eval_permutationColumnPolynomialOfResolver
assert_axioms eval_permutationCommonPolynomialOfResolver
assert_axioms eval_permutationChunkPairsOfResolver
assert_axioms eval_permutationChunksOfResolver
assert_axioms ConstraintSatisfaction.resolverPermutationConstraints
assert_axioms flattenPermutationChunkCell_injective
assert_axioms chunkRowName_injective_of_coset
assert_axioms replayKeygenPermutation_pair_linked
assert_axioms replayKeygenPermutation_sameCycle_iff
assert_axioms chunkPermutationOfFlat_apply
assert_axioms keygenSigmaColumn_eval
assert_axioms keygenSigmaColumn_natDegree_lt
assert_axioms ResolverPermutationDomain.ofCanonicalSelectors
assert_axioms ResolverPermutationCycle.ofKeygenColumns
assert_axioms mem_additiveZeroBadSet_iff
assert_axioms uniformChallenge_additiveZeroBadSet
assert_axioms mem_resolverPermutationZeroFactorBadSet_iff
assert_axioms uniformChallenge_resolverPermutationGammaBadSet
assert_axioms ConstraintSatisfaction.resolverPermutationCopyConstraints
assert_axioms CircuitConstraintFamily.operations_constraints_iff
assert_axioms FullCircuitSatisfaction.iff_constraints
assert_axioms FullCircuitSatisfaction.of_components_or_bad
assert_axioms CircuitConstraintFamily.copy_constraints_iff_declaredCopies
assert_axioms copy_constraints_or_bad_of_replay
assert_axioms CircuitConstraintFamily.lookup_constraints_iff_enabledLookups
assert_axioms foldPoly_injective_of_length_eq
assert_axioms eq_of_compressValues_eq_of_not_mem
assert_axioms EnabledLookup.thetaBadSet_card_le
assert_axioms uniformChallenge_enabledLookupThetaBadSet
assert_axioms EnabledLookup.satisfied_of_compressed
assert_axioms lookup_constraints_of_compressed
assert_axioms deployed_lookup_subset_of_nonzero_challenges
assert_axioms EnabledLookup.satisfied_of_deployed_subset
assert_axioms lookup_constraints_of_deployed_subsets
assert_axioms EnabledLookup.DeployedWitness.satisfied
assert_axioms lookup_constraints_of_deployed_witnesses
assert_axioms ResolverLookupDomain.ofCanonicalSelectors
assert_axioms ConstraintSatisfaction.resolverLookupSubset
assert_axioms gate_constraints_of_polynomial_witnesses
assert_axioms fixed_constraints_of_requirements
assert_axioms CopyReplayWitness.constraints_or_bad
assert_axioms FullCircuitBridge.ofPolynomialWitnesses
assert_axioms FullCircuitBridge.satisfaction_or_bad
assert_axioms FullCircuitBridge.constraints_or_bad
assert_axioms Zcash.Circuits.SynthesisWellFormed.of_usedRows
assert_axioms Zcash.Circuits.TopLevelCircuit.usedRows_le_usableRowsAt
assert_axioms Zcash.Circuits.TopLevelCircuit.fitsAt_domainExponent
assert_axioms Zcash.Circuits.TopLevelCircuit.synthesisWellFormed
assert_axioms Zcash.Bridge.powFast_eq_pow
assert_axioms Zcash.Bridge.omegaOf_isPrimitiveRoot +native
assert_axioms Zcash.Bridge.omegaOf_domain +native
assert_axioms Zcash.Bridge.omegaOf_powers_injective +native
assert_axioms FullCircuitSatisfaction.topLevelSoundness
assert_axioms FullCircuitBridge.topLevelSoundness_or_bad
assert_axioms TopLevelAssignment.synthesisWellFormed
assert_axioms rowPolynomial_eval
assert_axioms rowPolynomial_natDegree_lt
assert_axioms instanceRowPolynomial_eval
assert_axioms resolverEnvironment_instance_of_rowPolynomial
assert_axioms rowSelectorPolynomial_eq_basis
assert_axioms domainNodal_eq_vanishing
assert_axioms domainNodalWeight_eq
assert_axioms rowSelectorPolynomial_eval_eq_lagrangeBasisValue
assert_axioms rowSelectorPolynomial_eval_eq_lagrangeBasisValue_of_rotation
assert_axioms domain_pow_sub_eq_zpow_neg
assert_axioms blindSelectorPolynomial_eq_sum
assert_axioms blindSelectorPolynomial_eval_eq_lagrangeBasis
assert_axioms canonicalLagrangePolynomials_eval
assert_axioms rowSelectorPolynomial_eval
assert_axioms blindSelectorPolynomial_eval
assert_axioms firstSelectorPolynomial_nonzero
assert_axioms lastSelectorPolynomial_nonzero
assert_axioms last_add_blind_active
assert_axioms coeffsToPoly_polynomialCoefficients
assert_axioms rowPolynomial_eq_sum_single
assert_axioms polynomialCoefficients_rowPolynomial_eq_sum_single
assert_axioms coeffsToPoly_instanceCoefficients
assert_axioms LagrangeCommitmentKey.ofPrefix
assert_axioms LagrangeCommitmentKey.ofPrefix_generator_of_lt
assert_axioms LagrangeCommitmentKey.commitPrefix
assert_axioms LagrangeCommitmentKey.commitPrefixNat
assert_axioms LagrangeCommitmentKey.commitPrefixNat_eq_commitPrefix
assert_axioms LagrangeCommitmentKey.ofPrefix_commitInstance_eq
assert_axioms LagrangeCommitmentKey.commitRows_eq
assert_axioms LagrangeCommitmentKey.commitInstance_eq
assert_axioms instanceOpening_eq_or_relation
assert_axioms coeffsToPoly_eq_instanceRowPolynomial_or_relation
assert_axioms actionPublicInputs_of_instanceRowPolynomial
assert_axioms polynomialEnvironment_query_advice
assert_axioms polynomialEnvironment_query_fixed
assert_axioms polynomialEnvironment_query_instance
assert_axioms ActionAssignment.ofDecodedMembers_proofIndex
assert_axioms permutationLastEvalsWellFormed_of_assemble?_eq_some
assert_axioms eval_permutationDataOfDecodedResolver_or_relation
assert_axioms hgood_failure_priced
assert_axioms hgood_of_good_challenge
assert_axioms ComputedAlgebraicFSFamily.snarkExtractionFailureEvent_subset_union +native
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL_decomposed +native
assert_axioms fibered_accept_below_threshold_le
assert_axioms residual_le_of_coupling_containment
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL_unconditional +native
assert_axioms independentProductPMF_fiber_bound
assert_axioms residual_le_via_ladder +native
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL_ladder +native
assert_axioms multiopenPrefixReads_eq +native
assert_axioms multiopenLen_lt
assert_axioms multiopenChainAt_prefixes +native
assert_axioms multiopenLevelOf_prefixes +native
assert_axioms multiopenChainAt_ne
assert_axioms exists_multiopenStateAt_iff +native
assert_axioms multiopenPeelDecode_of_factors +native
assert_axioms snarkExtraction_prob_le_of_generatorRO_textbookDL_multiopen +native
assert_axioms memberBadEvent_measure_le
assert_axioms memberBadEvent_of_supply
assert_axioms honestCompletenessSupply_of_forkedTranscript
assert_axioms forkedTranscript_nonempty_of_instanceOpening +native
assert_axioms honestCompletenessSupply_of_instanceOpening +native
assert_axioms exists_ipaFoldChallenges
assert_axioms deployedAccepts_of_verifierEq
assert_axioms honestCompletenessSupply_of_openings_agree +native
assert_axioms honestCompletenessSupply_of_cleanOpening +native
assert_axioms honestCompletenessSupply_or_relation +native
assert_axioms fullAlgebraicAcceptDeployed +native
assert_axioms fullAlgebraicAccept_of_deployed +native
assert_axioms honestCompletenessSupply_of_cleanOpening_deployed +native
assert_axioms snarkExtractionFailureEventDeployed +native
assert_axioms snarkExtractionFailureEventDeployed_subset +native
assert_axioms snarkExtractionFailureEventDeployed_measure_le +native
assert_axioms updEsc
assert_axioms updEsc_blind
assert_axioms card_heavy_mul_le
assert_axioms updEsc_measure_le
assert_axioms updEsc_escapesDuringC_measure_le
assert_axioms adaptEsc
assert_axioms adapt_decomposition
assert_axioms adaptEsc_measure_le
